### ISSUE TITLE
Calculation of Correlations: Pearson’s Correlation OR Spearman’s Correlation?

### ISSUE THREAD

**Issue by malvela** [malvela/EnergyEfficientProcessIndustry#11]

**Comment by hluong679** [comment]
Der RapidMiner-Prozess, die Inputdaten sowie die Ergebnisse sind auf Seafile abrufbar. Die Korrelationmatrix wurde mit Hilfe des Prozesses erfolgreich erstellt. Auch die Namen der Attribute/ Parameter wurden bei der Erstellung der Matrix berücksichtigt. Des Weiteren können Sie genau den Prozess genau nach simmulieren. Sie brauchen RapidMiner nur 
![Korrelationsmatrix Farbe 2021-08-29](https://user-images.githubusercontent.com/84969012/131339019-05b8ba5a-2fbc-4d2e-a356-6d851ba1df1f.jpeg)
 installieren und dann die Prozessdatei importieren.
