### ISSUE TITLE
Combine RapidMiner with Tensorflow models?

### ISSUE THREAD

**Issue by malvela** [malvela/EnergyEfficientProcessIndustry#8]

**Comment by hluong679** [comment]
Ist möglich. RapidMiner hat KERAS als  API-Schnittstelle, um Libraries von TensorFlow, Microsoft Cognitive Toolkit oder Theano bei RapidMiner laufen zu lassen. Hier finden Sie die Beschreibung dazu:

https://community.rapidminer.com/discussion/36486/using-tensorflow

falls wir das Modell mit Pythons Libraries erstellen müssen, dann können wir trotzt dem dieses Modell bei RapidMiner laufen lassen und die Vorzüge von RapidMiner nutzen, um die Ergebnisse oder Daten zu visualisieren oder weiter zu bearbeiten.
